### ISSUE TITLE
upgrading issue

### ISSUE THREAD

**Issue by Wickett22** [Aton-Kish/reinforced-shulker-boxes#12]
Having a strange issue with upgrading boxes. After crafting an upgraded version, which works great with both rei and normal, the mod will not let you do it again. only works once with all schematics. tried both through rei and manual. using a different station does not help. Makes me relog in every time. Dont know if this is a possible Mod conflict or bug.

**Comment by Aton-Kish** [comment]
Thank you for reporting.
Just to confirm, is the reproduction method as follows?

1. REI shows upgrading recipes
2. You craft and upgrade a shulker box with a crafting table
3. The upgrading recipe disappears from REI until re-login.
    - ~At this time, the vanilla recipe is fine.~ vanilla recipe is also broken...

~I've confirmed that the vanilla recipe didn't seem to cause any problems, but please point out any misunderstandings.~

The REI's recipe issue is a bug.
I'm modifying the recipe type to keep the items of shulker boxes when upgraded.
I think that customized recipe type is the cause of the bug.

**Comment by Aton-Kish** [comment]
@Wickett22 
Probably fixed in version 1.1.5.
<https://www.curseforge.com/minecraft/mc-mods/reinforced-shulker-boxes>
If you still have problems, please re-open this issue.
