### ISSUE TITLE
some shulkerbox recipes are broken

### ISSUE THREAD

**Issue by xStellari** [Aton-Kish/reinforced-shulker-boxes#15]
hi! some of the shulkerbox recipes are broken like the yellow shulkerbox. I can't upgrade it to gold onwards. Tried checking the yellow gold shulkerbox recipe using REI (i'm using fabric) and it's not showing the recipe but it shows the recipe for iron, copper and dia. Pretty sure yellow is not the only shulker that has broken recipes (i encountered more) but that's the only thing I can remember as I'm writing this. Thank you!

**Comment by Aton-Kish** [comment]
@xStellari 
Please check the version you are using.
If version 1.1.4 or lower, can you try version 1.1.5?
The recipe bug was already reported #12 and I think it was fixed in version 1.1.5.
