### ISSUE TITLE
Reinforced Shulkers: Vanilla Hoppers and AE2 networks can only access the first 27 inventory slots.

### ISSUE THREAD

**Issue by RubyRezal** [Aton-Kish/reinforced-shulker-boxes#19]
Minecraft 1.18.1
Fabric 0.12.12
Reinforced Shulkers 1.1.5 (Haven't had the opportunity to upgrade our server to 1.1.6 yet.)

It seems that Vanilla hoppers and AE2 ME network elements (Storage Bus, Import Bus, and Export Bus) are unable to access the additional inventory space in Reinforced Shulkers. Tom's Simple Storage does not appear to have this problem.

Prepared Shulker for demonstration of issue:
![2021-12-30_15 14 37](https://user-images.githubusercontent.com/1816386/147785707-a16d55f3-be9b-4c24-a416-1ed60b5627db.png)

Shulker as it appears in Tom's Simple Storage:
![2021-12-30_15 15 19](https://user-images.githubusercontent.com/1816386/147785802-769c3d54-ad66-4a46-9a74-3f579abd25cf.png)

Shulker as it appears in AE2 ME Terminal:
![2021-12-30_15 15 25](https://user-images.githubusercontent.com/1816386/147785839-eb74c714-553c-4930-abf8-2aecfbe6d511.png)

Vanilla Hoppers only perform I/O operations on the first 27 inventory slots.

**Comment by RubyRezal** [comment]
Basic Inventory Hoppers from Tom's Simple Storage Mod are also unable to perform I/O on inventory beyond the first 27 slots.

This issue does not affect Reinforced Chests.

**Comment by Aton-Kish** [comment]
@Xastabus Thanks again<3
probably fixed in version 1.1.7.
but, I'm not familiar with AE2... so, I want you to check it if possible.

**Comment by RubyRezal** [comment]
AE2 can view and Import/Export the full contents of Reinforced Shulkers in version 1.1.7.  Thanks!
