### ISSUE TITLE
Future Upgrade Options!

### ISSUE THREAD

**Issue by JonCaver** [Aton-Kish/reinforced-shulker-boxes#2]
Hello!
First off great mod(s)!!
Would it be possible for you to update the mod so it will work with the GUI of other mods like "REI","Shulkerboxtooltip"?
or just have it label what stacks are inside of the shulkers?
No rush or anything just and idea to help this mod work well with others.
Cheers!!

**Comment by Aton-Kish** [comment]
OK, I'll try.
I think REI is working, but isn't it?

**Comment by Aton-Kish** [comment]
In [version 1.1.0](https://www.curseforge.com/minecraft/mc-mods/reinforced-shulker-boxes/files/3469088)
- integrate with [ShulkerBoxTooltip](https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip)
- integrate with [Quick Shulker](https://www.curseforge.com/minecraft/mc-mods/quick-shulker)

**Comment by tealtonic** [comment]
Hey, would it also be possible for mod compatibility with Trinket Shulkers? Would be super cool, so long as it's not too much work of course!

**Comment by JonCaver** [comment]
Thank you!! REI does work. Before this update there was no darker overlay to the background while inside the shulkerbox making it hard to see the REI items. but it is working fine in this update!! Thanks again!!

**Comment by Aton-Kish** [comment]
@tealtonic 
I have created an issue for Trinket Shulker Boxes
https://github.com/TheIllusiveC4/CuriousShulkerBoxes/issues/11
