### ISSUE TITLE
[Bug] Instant access to copper/all tiers of shulkers

### ISSUE THREAD

**Issue by Mj11jM** [Aton-Kish/reinforced-shulker-boxes#27]
### Describe the bug

Instant access to Copper/All tiers of shulkers if reinforced chests are not installed.

### To Reproduce

Have only reinforced shulkers installed and attempt to use the recipe for if reinforced chests are installed, by default it gives you a copper shulker box. If polymorph is installed, letting you choose from recipe conflicts, all tiers are available.

### Expected behavior

That recipe shouldn't be registered if the chest mod is not installed

### Screenshots

[A Screenshot showing the default recipe and the options with polymorph installed.](https://i.imgur.com/NUJAUI2.png)

### Environment

- Minecraft: 1.18.1
- Fabric Loader: 0.13.1 + 0.12.12
- Fabric API: 0.46.4+1.18
- Shulker Version: 2.0.0-beta.1+1.18

**Comment by Aton-Kish** [comment]
Thank you for reporting!
In version 2.0.0-beta.2+1.18, this issue is fixed.
I will also fix version 1.x.x later because they still have a problem.
