### ISSUE TITLE
[Bug] Mixin conflict between Reinforced Shulker Boxes and Reinforced Barrels

### ISSUE THREAD

**Issue by Sunconure11** [Aton-Kish/reinforced-shulker-boxes#33]
https://pastebin.com/ERCq0DzX

**Comment by Aton-Kish** [comment]
There is no doubt that there is a conflict, but it's just "WARN" and I don't think the cause of the error.

**Comment by Aton-Kish** [comment]
If there are still any problems with my Mods, please re-open this.
