### ISSUE TITLE
[Bug]Recipes containing chest can be crafted even without the ReinforcedChest mod

### ISSUE THREAD

**Issue by NoneMore** [Aton-Kish/reinforced-shulker-boxes#42]
Leading to this issue
![QQ截图20220920192523](https://user-images.githubusercontent.com/31123633/191245672-f6688e67-92e9-47c9-93b3-85c2a4446748.png)
Mod verision 1.1.8 for Mineraft version 1.17.1
The mod ExpandedStorage is also installed and has similar reinforced chests in your mod,I don't know if that makes a difference

**Comment by Aton-Kish** [comment]
This issue had been reported in #27 and fixed in #28 (ONLY above 1.18).
Today, I ported it to 1.17.
