### ISSUE TITLE
[Feature 1.19.2] Can you add recipies to dye premade boxes?

### ISSUE THREAD

**Issue by DemonSlayer112** [Aton-Kish/reinforced-shulker-boxes#53]
Idea:
Dyeable boxes that keep nbt(red copper -> yellow copper)

I relize i could add this to my pack via kubejs but its a nice thought to throw out there for the mod in general.
As well as an undying recipe. Ty for the read :)

Also! for a second idea, could there be a config for a harder netherite crafting recipe? A full netherite block :D
Makes the netherite tier so much more valuable.

**Comment by Aton-Kish** [comment]
> Idea:
Dyeable boxes that keep nbt(red copper -> yellow copper)

Dyeing and undyeing are already supported. Can you try it?
https://github.com/Aton-Kish/reinforced-shulker-boxes#dyeing

> Also! for a second idea, could there be a config for a harder netherite crafting recipe?

The recipe file format is very simple. I think you could rewrite recipe files directly by unzipping the mod jar. As it's not clear how much customization would be nice, I'm not going to support it now.

**Comment by DemonSlayer112** [comment]
Oh ty!
Sorry, haven't relized, the recipes weren't showing in REI so i assumed they weren't there xD
And fair enough, but i might have to skip the mod editing due to curseforge being picky with that, for now i suppose i can edit with kubejs, ty for the mod :D
