### ISSUE TITLE
[Bug] Piston cannot break Reinforced Shulker Boxes

### ISSUE THREAD

**Issue by Grayer0113** [Aton-Kish/reinforced-shulker-boxes#61]
### Screenshots

![image](https://github.com/Aton-Kish/reinforced-shulker-boxes/assets/58380260/0195471e-6ceb-4ceb-8002-61dbdb8a16c8)

### Environment

- Minecraft: [1.20.1]
- Fabric Loader: [0.14.22]
- Fabric API: [0.86.1+1.20.1]

**Comment by TprScruffy** [comment]
![2023-08-04_16 16 48](https://github.com/Aton-Kish/reinforced-shulker-boxes/assets/111855278/a7eb5564-2bb8-4c96-b81f-a72e6a868c57)
Yes I have the same issue. Should hopefully be a quick fix. This broke my 8x hopper speed, shulker box unloader that goes to my fully auto sorter. 
![2023-08-04_16 20 04](https://github.com/Aton-Kish/reinforced-shulker-boxes/assets/111855278/56f18013-5745-40b3-be2f-4c3d07b4d33f)

**Comment by Aton-Kish** [comment]
fixed in version 2.5.0
