### ISSUE TITLE
[Bug] Increase Compatibility by adding to the minecraft:blocks/shulker_boxes block tag

### ISSUE THREAD

**Issue by coolsimulations** [Aton-Kish/reinforced-shulker-boxes#69]
### Add a block data tag to add all shulkers to the `minecraft:blocks/shulker_boxes` tag

In vanilla this tag is used to prevent walls, fences, etc to connect to shulker boxes. As it is Reinforced Shulkers go against this behaviour. A similar mod, [Iron Shulker Boxes](https://www.curseforge.com/minecraft/mc-mods/iron-shulker-boxes) add this [tag](https://github.com/progwml6/ironshulkerboxes/blob/1.20.x/src/generated/resources/data/minecraft/tags/blocks/shulker_boxes.json).

![2024-04-14_17 32 15](https://github.com/Aton-Kish/reinforced-shulker-boxes/assets/33711385/38f1fefc-6185-4a64-b407-5a814bbe148d)

Currently, I am adding an item to my mod [SurvivalPlus](https://www.curseforge.com/minecraft/mc-mods/survivalplus) which uses shulkers and detects valid shulkers using this tag, so right now it's not detecting any shulkers from this mod.

**Comment by Aton-Kish** [comment]
Thank you for your report. It will be fixed in v2.5.3+1.20.4.
