### ISSUE TITLE
[Feature] Support for ShulkerBox ToolTip

### ISSUE THREAD

**Issue by PhyroStyx** [Aton-Kish/reinforced-shulker-boxes#78]
### Describe the solution you'd like

Finding things in large storage containers is quite the hassle especially in shulker boxes. I have to place them first to see the contents inside and possibly miss what Im looking for. That's why I would like to add a feature where you can preview shulker boxes using keybinds inside of inventory to see the contents inside. And that's where ShulkerBox Tooltip come to play. 

I request to please add a feature to shulkerbox tooltip mod to be able to see whats inside the upgraded shulker boxes.

### Additional context

![image](https://github.com/Aton-Kish/reinforced-shulker-boxes/assets/173194970/90e038e2-5adf-4d09-891e-16025bf7841e)

**Comment by elnoelsi** [comment]
+1 please

**Comment by Aton-Kish** [comment]
In version 3.1.0, this mod has been re-integrated with the shulker box tooltip.
